### ISSUE TITLE
Does not run on Processing 3.0.2 with ControlP5 2.2.5

### ISSUE THREAD

**Issue by Isaac96** [multiwii/multiwii-gui-processing#3]
What the title says-ControlP5 latest version is not compatible.

**Comment by BrianBot24** [comment]
The code is to upgrade, but still is a great contribution

**Comment by Isaac96** [comment]
Gotta agree. But they need to speed it up :)

**Comment by f41ardu** [comment]
Unfortunately I run in the same issue. You need Processing 2.2.1 and an older release of controlP5  library (My version of ControlP5 is 2.0.4).  I just start to look at the changes in controlP5 but there are multiple changes in the library and related Processing calls.

**Comment by techboycr** [comment]
I made the changes for the GUI to work with the latest versions of  Processing and ControlP5, yo can find it here:

https://github.com/techboycr/multiwii-gui-processing

Let Me know if something is not working quite well, I'll fix right away.

Happy Flying!

**Comment by nancxjo** [comment]
Hey, I've duplicated your efforts @techboycr and got my version to work with processing 2 and the new version of controlP5. It's because I didn't see your fork. Any chance of you committing your patch to the main repository for prosperity?

**Comment by techboycr** [comment]
@nancxjo sure I can do that!

DONE!!

Let me know any issue.

**Comment by techboycr** [comment]
If @nancxjo test it and confirm that works maybe @Isaac96 can close this issue.

**Comment by nancxjo** [comment]
@techboycr I can confirm it is 100% functional. I've noticed minor graphical issues, but nothing that undermines the functionality of the gui.

**Comment by techboycr** [comment]
Awesome @nancxjo enjoy!

**Comment by Isaac96** [comment]
In that case, issue closed :D

**Comment by BrianBot24** [comment]
gracias :D  a todos por el apoyo
